services:
  backend:
    build: SingleBack
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=singlepage
      - MYSQL_ROOT_PASSWORD=huangz1
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - spring-mysql
  frontend:
    build: singlepage
    ports:
      - 3000:3000
    volumes:
      - ./singlepage/src:/code/src
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend
    expose:
      - 3306
      - 33060
networks:
  react-spring: {}
  spring-mysql: {}

